language:
  - c
before_install:
  - apt-get install gfortran
  - gem install funit
  - export FC="gfortran"
  - export FSFLAG=-I
  - export CXX="g++"
  - export CC="gcc"
os:
  - linux
script:
  - gfortran -fprofile-arcs -ftest-coverage -O0 circle_class.f90 -o circle_class
  - ./circle_class

