language: 
  - cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang34
        apt:
          packages:
            - clang
            - cmake3
            - gfortran
            - swig
      env:
        - FC="gfortran"
        - FSFLAG=-I
        - CXX="g++"
        - CC="gcc"
        # - CXX_COMPILER='clang++'
        # - C_COMPILER='clang'
        # - Fortran_COMPILER='gfortran'
        # - BUILD_TYPE='Release'
        # - PYTHON='--three'
        # - COVERAGE=OFF
before_install:
  - gem install funit
script:
  - funit circle_class
  - ./circle_class

